# Generated by Django 5.0.14 on 2026-09-23 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Pulses', 'Pulses'), ('Spices', 'Spices'), ('Root Crops', 'Root Crops'), ('Other', 'Other')], default='Vegetables', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_of_measure', models.CharField(default='kg', max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD', 'Sold'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=20)),
                ('product_type', models.CharField(choices=[('FARMER_LISTING', 'Farmer Listing'), ('WHOLESALER_LISTING', 'Wholesaler Listing')], max_length=25)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
