# Generated by Django 5.0.14 on 2026-09-27 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('FARMER_LISTING', 'Farmer Listing'), ('WHOLESALER_LISTING', 'Wholesaler Listing')], default='FARMER_LISTING', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD', 'Sold'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Metric ton'), ('piece', 'Piece'), ('crate', 'Crate'), ('bunch', 'Bunch'), ('litre', 'Litre')], default='kg', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'product_type'], name='products_owner_i_900753_idx'),
        ),
    ]
