# Generated by Django 5.0.14 on 2026-09-27 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('products', '0003_alter_product_product_type_alter_product_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('CBE Birr', 'CBE Birr'), ('Telebirr', 'Telebirr'), ('Bank Transfer', 'Bank Transfer'), ('Chapa', 'Chapa'), ('Cash', 'Cash')], default='CBE Birr', max_length=100),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['wholesaler', 'status'], name='orders_wholesa_15cb28_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['status', 'submitted_at'], name='payment_rec_status_2f5ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['submitted_by', 'status'], name='payment_rec_submitt_c93484_idx'),
        ),
    ]
