# Generated by Django 5.2.18 on 2026-10-09 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_businessagreement_review_wallet_walletfundingrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfundingrequest',
            name='checkout_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='payment_mode',
            field=models.CharField(default='MANUAL', max_length=8),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='provider_transaction_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='verified_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='walletfundingrequest',
            name='verified_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='walletfundingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending verification'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_VERIFICATION_PENDING', 'Payment Verification Pending'), ('AWAITING_APPROVAL', 'Awaiting Financial Admin Approval'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='walletfundingrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_funding_idempotency_key'),
        ),
    ]
