# Generated by Django 5.2.18 on 2026-10-09 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def add_registered_ethiopian_banks(apps, schema_editor):
    PayoutBank = apps.get_model("payments", "PayoutBank")
    source = "https://nbe.gov.et/financial-institutions/banks/"
    banks = (
        ("commercial-bank-of-ethiopia", "Commercial Bank of Ethiopia"),
        ("awash-bank", "Awash Bank"),
        ("dashen-bank", "Dashen Bank"),
        ("bank-of-abyssinia", "Bank of Abyssinia"),
        ("wegagen-bank", "Wegagen Bank"),
        ("hibret-bank", "Hibret Bank"),
        ("nib-international-bank", "Nib International Bank"),
        ("zemen-bank", "Zemen Bank"),
        ("cooperative-bank-of-oromia", "Cooperative Bank of Oromia"),
        ("oromia-bank", "Oromia Bank"),
        ("berhan-bank", "Berhan Bank"),
        ("addis-international-bank", "Addis International Bank"),
        ("enat-bank", "Enat Bank"),
        ("bunna-bank", "Bunna Bank"),
        ("debub-global-bank", "Debub Global Bank"),
        ("amhara-bank", "Amhara Bank"),
        ("hijra-bank", "Hijra Bank"),
        ("zamzam-bank", "ZamZam Bank"),
    )
    PayoutBank.objects.using(schema_editor.connection.alias).bulk_create(
        [
            PayoutBank(code=code, name=name, source_url=source)
            for code, name in banks
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_walletfundingrequest_checkout_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('source_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payout_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number_encrypted', models.TextField()),
                ('account_number_last4', models.CharField(max_length=4)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('branch_code', models.CharField(blank=True, default='', max_length=40)),
                ('account_type', models.CharField(blank=True, default='', max_length=40)),
                ('nickname', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('NOT_VERIFIED', 'Not verified'), ('REQUIRES_REVIEW', 'Requires further review')], default='NOT_VERIFIED', max_length=24)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='payments.payoutbank')),
            ],
            options={
                'db_table': 'user_bank_accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='walletpayoutrequest',
            name='payout_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='payments.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['user', 'status', 'is_default'], name='user_bank_a_user_id_f1cc9e_idx'),
        ),
        migrations.RunPython(add_registered_ethiopian_banks, migrations.RunPython.noop),
    ]
