# Generated by Django 5.2.18 on 2026-10-09 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_presence_sessions',
                'indexes': [models.Index(fields=['user', 'disconnected_at', 'last_seen_at'], name='user_presen_user_id_5ca843_idx')],
            },
        ),
    ]
